project:
  type: website


engine: julia
# engines: ['julia','jupyter']


execute:
  freeze: auto  # re-render only when source changes
  # cache: true

# julia:
#   key: value

# The currently available options are:

# exeflags: An array of strings which are appended to the julia command that starts the worker process. For example, a notebook is run with --project=@. by default (the environment in the directory where the notebook is stored) but this could be overridden by setting exeflags: ["--project=/some/directory/"].
# env: An array of strings where each string specifies one environment variable that is passed to the worker process. For example, env: ["SOMEVAR=SOMEVALUE"].



author: 
  name: "Jarda Půlpán"
  email: "pulpanj@volny.cz"
lang: cs
date-format: iso

website:
  description: "Blog psaný na základě přednášek university 3 věku na MFF UK: Náhoda, nelinearita, chaos, komplexita. Moderní příspěvky fyziky k porozumění světu kolem nás."
  site-url: http://www.pulpanj.me.cz/blogs/u3v/s1_nahoda_chaos/ # you must change this appropriately for RSS feeds to work properly
  title: "U3V_1> Náhoda, nelinearita, chaos, komplexita"
  open-graph: true
  # navbar:

  # margin-header: |
  #   ![Logo image](/images/pdf-icon.jpg)
  #   #toc

  # sidebar:
  #   - title: "cheese"
  #     style: "docked"
  #     sidebar-position: right
  #     background: dark
  #     contents: 
  #       - text: "Blog"
  #         href: index.qmd
  #       - text: "O čem je kurz"
  #         href: ocem.qmd        

  #   - title: "badger"
  #     contents:
  #       - text: "------"
  #       - text: "------"
  #       - text: "------"
  #       - index.qmd
  #       # navigation items

  page-navigation: true
  back-to-top-navigation: true
  search:
    location: navbar
    type: textbox

  navbar:
    right:
      - text: Kurz
        menu:
          - ./ocem.qmd
          - literatura.qmd
      - text: Manuály
        menu:
          - text: Quarto ve VSC
            href: https://quarto.org/docs/get-started/hello/vscode.html
          - text: Julia language
            href: https://julialang.org/
      - icon: file-earmark-person
        href: ./aboutme.qmd
        text: " "
      - icon: github
        href: https://github.com/Pulpanj/s1_nahoda_chaos
      - icon: envelope
        href: email:pulpanj@volny.cz
    #   - icon: rss
    #     href: index.xml
    # left:
    #   - stuff/item1.qmd
    #   - stuff/item2.qmd

  page-footer:
    border: true
  # Theme default
    background: rgb(81, 118, 153)
    foreground: rgb(221, 228, 235)
    # center:
    #   - text: "About"
    #     href: about.qmd
    left:
      - text: © 2025 <a href=/aboutme.qmd> Jarda Půlpán  </a>
      # - link: "pulpanj@volny.cz"
    center:
      - Kódy v jazyce <a href=https://julialang.org/>Julia</a>, generováno pomoci <a href=https://quarto.org/>Quarto</a>
    right:
      - text: "Licence: <a href=https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1>CC BY 4.0</a>"

  # comments:
  #   hypothesis:
  #     theme: classic
  #     openSidebar: false
  #     showHighlights: whenSidebarOpen
  #     enableExperimentalNewNoteButton: true
  #     branding:
  #         appBackgroundColor: white
  #         # theme: default
  #         ctaBackgroundColor: rgb(81, 118, 153)
  #         ctaTextColor: rgb(221, 228, 235)
  #         selectionFontFamily: 'helvetica, arial, sans serif'

  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Varování** - tento blog je stále ve výstavbě, časem přidám i materialy z počátečních seancí. "
    type: primary
    position: below-navbar  
  # reader-mode: true            


format:
  # typst:
  #   toc: true
  #   number-sections: true
  #   toc-depth: 4       # Optional: controls heading levels shown
  #   number-depth: 4
  html:
    toc: true
    number-sections: false
    toc-depth: 4       # Optional: controls heading levels shown
    toc-expand: false
    smooth-scroll: true
    theme:
        # - lux,cosmo
        # - brand
        light: brand
        dark: slate
    code-fold: true
    code-tools:
      source: true
      toggle: false
      caption: qmd
    page-layout: article
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 50px
      gutter-width: 1.5rem      

css: styles.css
# template: html.template
